
#dhrystone.elf: dhrystone_main.o dhrystone.o syscalls.o | dhrystone.E dhrystone_main.E
dhrystone.hex: dhrystone_main.o dhrystone.o syscalls.o | dhrystone.E dhrystone_main.E

CFLAGS += -DENTRY_POINT=main

include ../common/Makefile
