
dhrystone.hex: dhrystone_main.o dhrystone.o | dhrystone.E dhrystone_main.E syscalls.E

#CFLAGS+=-DToo_Small_Time=0 -DNUMBER_OF_RUNS=1 -DDEBUG_RUNTIME
#CFLAGS+=-DDEBUG_RUNTIME

include ../common/Makefile
